import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Layout/Header";
import MainNavigation from "@/components/Layout/MobileMenu";
import Footer from "@/components/Layout/Footer";

export const metadata: Metadata = {
  title: "NFT Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Header />
        <div className="min-h-[80vh]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
